export const MENU = [
    {
        title: 'Greek salad',
        price: 12.99,
        urlOrder: "#",
        alt: "Greek salad with lettuce, peppers, olives, and feta cheese garnished with garlic and rosemary croutons",
        urlImage: "/greek-salad.webp",
        description: "The famous greek salad of crispy lettuce, peppers, olives and our Chicago style feta cheese, garnished with crunchy garlic and rosemary croutons.",
    },
    {
        title: 'Bruchetta',
        price: 8.99,
        urlOrder: "#",
        alt: "Grilled bread topped with garlic, salt, and olive oil",
        urlImage: "/bruchetta.webp",
        description: "Our Bruschetta is made from grilled bread that has been smeared with garlic and seasoned with salt and olive oil.",
    },
    {
        title: 'Lemon Dessert',
        price: 5.99,
        urlOrder: "#",
        alt: "Delicious lemon dessert made from Grandma's recipe book",
        urlImage: "/lemon-dessert.webp",
        description: "This comes straight from grandma's recipe book, every last ingredient has been sourced and is as authentic as can be imagined.",
    },
    {
        title: 'Grilled Salmon',
        price: 19.99,
        urlOrder: "#",
        alt: "Grilled salmon fillet served with lemon butter sauce",
        urlImage: "/grilled-salmon.webp",
        description: "A tender grilled salmon fillet, served with a rich lemon butter sauce and a side of seasonal vegetables.",
    },
    {
        title: 'Margherita Pizza',
        price: 10.99,
        urlOrder: "#",
        alt: "Classic Margherita pizza with fresh tomatoes, mozzarella, and basil",
        urlImage: "/margherita-pizza.webp",
        description: "A classic Margherita pizza topped with fresh tomatoes, mozzarella, and basil, baked to perfection.",
    },
    {
        title: 'Spaghetti Carbonara',
        price: 14.99,
        urlOrder: "#",
        alt: "Spaghetti carbonara with pancetta, egg, and Parmesan",
        urlImage: "/spaghetti-carbonara.webp",
        description: "Creamy spaghetti carbonara made with pancetta, egg, and Parmesan cheese, tossed to perfection.",
    },
    {
        title: 'Chicken Caesar Wrap',
        price: 9.99,
        urlOrder: "#",
        alt: "Chicken Caesar wrap with romaine lettuce, grilled chicken, and Caesar dressing",
        urlImage: "/chicken-caesar-wrap.webp",
        description: "Grilled chicken wrapped with fresh romaine lettuce, croutons, and Caesar dressing in a soft tortilla.",
    },
    {
        title: 'Vegetable Stir Fry',
        price: 11.99,
        urlOrder: "#",
        alt: "Mixed vegetables stir-fried with a soy-ginger sauce",
        urlImage: "/vegetable-stir-fry.webp",
        description: "A healthy and colorful mix of stir-fried vegetables in a tangy soy-ginger sauce, served with jasmine rice.",
    },
    {
        title: 'Beef Tacos',
        price: 8.49,
        urlOrder: "#",
        alt: "Soft tacos filled with seasoned beef, lettuce, cheese, and salsa",
        urlImage: "/beef-tacos.webp",
        description: "Soft tacos filled with seasoned beef, fresh lettuce, cheese, and a house-made salsa, served with lime wedges.",
    },
    {
        title: 'Chocolate Lava Cake',
        price: 6.99,
        urlOrder: "#",
        alt: "Rich chocolate lava cake with a warm, gooey center",
        urlImage: "/chocolate-lava-cake.webp",
        description: "Indulge in our rich chocolate lava cake, with a warm, gooey center that melts in your mouth.",
    },
    {
        title: 'Caprese Salad',
        price: 9.99,
        urlOrder: "#",
        alt: "Fresh Caprese salad with tomatoes, mozzarella, and basil",
        urlImage: "/caprese-salad.webp",
        description: "A refreshing Caprese salad made with ripe tomatoes, fresh mozzarella, and basil, drizzled with balsamic glaze and olive oil.",
    },
    {
        title: 'BBQ Ribs',
        price: 17.99,
        urlOrder: "#",
        alt: "Tender BBQ ribs glazed with house-made barbecue sauce",
        urlImage: "/bbq-ribs.webp",
        description: "Slow-cooked, fall-off-the-bone ribs glazed with our signature barbecue sauce, served with coleslaw and fries.",
    }
];
